### PR TITLE
Update Spglib version

### PR DESCRIPTION
**Pull request by mfherbst**
Should not cause any issues as changes are in parts of the code not concerned with this.

### CODE REVIEW

**Comment by thchr** [comment]
Ah, thanks!

**Comment by singularitti** [comment]
Should it be `"0.8, 0.9"`? I don't think `Brillouin.jl` itself rely on the functionalities introduced in `v0.9`?

**Comment by mfherbst** [comment]
True. My bad. Feel free to fix.

**Comment by singularitti** [comment]
Thanks! See #29.

**Pull request merged**
