### PR TITLE
Fixes to BrillouinSpglibExt as suggested in #26

### PR DESCRIPTION
**Pull request by mfherbst**

### CODE REVIEW

**Comment by thchr** [comment]
Thanks! This should probably also bump the version of Spglib in Project.toml:

https://github.com/thchr/Brillouin.jl/blob/1aa1e322bdb971837adff48547342fd8c32e17bf/Project.toml#L35

**Comment by mfherbst** [comment]
For sure ! Thanks @thchr

**Comment by mfherbst** [comment]
These failures look like they are due to changes in the ordering of matrices (rows versus columns etc.) @singularitti any idea which of your changes could cause this ?

**Comment by singularitti** [comment]
I probably transposed some matrices to align with Spglib's mathematical convention. I will have a look at these errors.

**Comment by mfherbst** [comment]
Got it. It actually was that @singularitti plus a small inconsistency in the code.

**Comment by singularitti** [comment]
Alright, I've reviewed your code and compared it to my convention. It appears that Michael's fix is indeed correct.

In Spglib's convention, when you transform the reference axes, you apply the transformation matrix by multiplying it on the right, denoted as `P`:

Transformation

However, when you rotate the axes during idealization, you multiply the rotation matrix `R` on the left:

Rotation

I realized that in versions prior to v0.8, I was using the wrong convention, which resulted in the `rotation` matrix being the transpose of the current convention. Interestingly, this happened to align with your convention.

I'm also checking if `dataset.transformation_matrix` might be affected by this change. @mfherbst, did you use `dataset.transformation_matrix` in your code?

Apart from that, I have conducted extensive tests since v0.8, and it seems that the current convention is indeed the correct one.

I have a couple of suggestions:

1. Consider changing `points(kp)[lab] = rotation' * kv` to `points(kp)[lab] = transpose(rotation) * kv`. Using `transpose` makes it more explicit and easier to understand.

2. Instead of `eachcol`, you can use `pRs = SVector{3}(Spglib.basisvectors(dset.std_lattice))` and `pRs_original = SVector{3}(Spglib.basisvectors(cell.lattice)`. These are part of the official API I provided, which can enhance code readability and maintainability.

Feel free to let me know your thoughts or if you have any further questions!

**Comment by thchr** [comment]
And thanks for double checking everything @singularitti: really nice to have it settled and carefully checked.

**Comment by mfherbst** [comment]
Thanks for the comments @singularitti. I changed the code according to your second suggestion. I don't think the first is worth it: In Julia the tick is quite wide-spread to transpose a matrix and the comment should make clear why.

**Comment by mfherbst** [comment]
Good to go from my end now @thchr !

**Comment by thchr** [comment]
Brilliant; many thanks!

**Pull request merged**
